version: '3'
services:
 testy:
  build: .
  ports:
  - "${TASTYIGNITER_HOST_HTTP_PORT}:80"
  environment:
  - MYSQL_HOSTNAME=mysql
  - MYSQL_DATABASE=${DB_DATABASE}
  - MYSQL_USER=${DB_USER}
  - MYSQL_PASSWORD=${DB_PASSWORD}
  - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  restart: always
  volumes:
    - ${APP_CODE_PATH_HOST}:/var/www/html
 mysql:
  image: mariadb
  volumes:
  - ${DATA_PATH_HOST}:/var/lib/mysql
  environment:
  - MYSQL_RANDOM_ROOT_PASSWORD=yes
  - MYSQL_DATABASE=${DB_DATABASE}
  - MYSQL_USER=${DB_USER}
  - MYSQL_PASSWORD=${DB_PASSWORD}
  restart: always
volumes:
  db_data:
    driver: local
